adx_append: false
adx_appendto: false
adx_create: false
adx_delete: false
adx_entitylogicalname: sxp_configuration
adx_entityname: CSSP - Configuration
adx_entitypermission_webrole:
- 6f2449bf-9988-4db2-b4b7-42a52c931cc5
- 844598bc-d0cb-410a-b2de-b6f2c4dbc487
adx_entitypermissionid: aa32f47d-a437-ec11-b6e6-000d3a994e43
adx_read: true
adx_scope: 756150000
adx_write: false
