adx_displayorder: 2
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_isroot: false
adx_name: Application Inventory
adx_pagetemplateid: 7b17a527-566f-ed11-9562-000d3a8c6ab8
adx_parentpageid: 96f5a62d-566f-ed11-9562-000d3a8c6ab8
adx_partialurl: Application-Inventory
adx_publishingstateid: bb17a527-566f-ed11-9562-000d3a8c6ab8
adx_rootwebpageid: b4e72db9-66b8-9e96-c89f-ba167cca7117
adx_sharedpageconfiguration: true
adx_title: Application Inventory
adx_webpageid: 0529ca5a-2fc2-f07f-6318-dc3e8656b155
adx_webpagelanguageid: 302eab33-566f-ed11-9562-000d3a8c6ab8
