adx_calendar_enabled: false
adx_createbuttonlabel: >-
  [
    {
      "LCID": 1033,
      "Value": ""
    }
  ]
adx_entitylistid: ebd15046-1478-ed11-81ab-000d3a8c6ab8
adx_entityname: ava_application
adx_entitypermissionsenabled: true
adx_filter_enabled: false
adx_filterportaluser: ava_contactapplicant
adx_idquerystringparametername: id
adx_map_distancevalues: 5,10,25,50,100
adx_map_enabled: false
adx_map_infoboxoffsetx: 25
adx_map_infoboxoffsety: 46
adx_map_pushpinheight: 39
adx_map_pushpinwidth: 32
adx_map_resturl: https://dev.virtualearth.net/REST/v1/Locations
adx_map_zoom: 12
adx_name: Application List
adx_odata_enabled: false
adx_pagesize: 10
adx_searchenabled: true
adx_settings: >-
  {
    "Type": "CrmEntityFormView-GridMetadata",
    "ViewFormats": [],
    "ViewActions": [],
    "ExtendedViewActions": [],
    "ItemActions": [
      {
        "Type": "CrmEntityFormView-EditAction",
        "SuccessMessage": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": "The record has been saved."
          }
        ],
        "RecordIdQueryStringParameterName": "id",
        "TargetType": 1,
        "OnComplete": 0,
        "RedirectWebpageId": "e4144c9b-ce7b-ed11-81ad-000d3a8c6ab8",
        "RedirectUrl": "",
        "EntityFormId": "",
        "ShowModal": 0,
        "Confirmation": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          }
        ],
        "ButtonLabel": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": "Edit"
          }
        ],
        "ButtonTooltip": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          }
        ],
        "ActionIndex": 0,
        "FilterCriteria": ""
      }
    ],
    "ExtendedItemActions": [],
    "ColumnOverrides": [],
    "LoadingMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      }
    ],
    "ErrorMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      }
    ],
    "AccessDeniedMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      }
    ],
    "EmptyMessage": [
      {
        "Type": "LanguageResources",
        "LCID": 1033,
        "Value": ""
      }
    ],
    "DetailsFormDialog": {
      "Type": "CrmEntityFormView-DetailsFormModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "EditFormDialog": {
      "Type": "CrmEntityFormView-EditFormModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "CreateRelatedRecordDialog": {
      "Type": "CreateRelatedRecordModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "CreateFormDialog": {
      "Type": "CrmEntityFormView-CreateFormModal",
      "LoadingMessage": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "DeleteDialog": {
      "Type": "CrmEntityFormView-GridDeleteModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "WorkflowDialog": {
      "Type": "WorkflowModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "ErrorDialog": {
      "Type": "CrmEntityFormView-ErrorModal",
      "Body": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "CssClass": "",
    "GridCssClass": "table-striped",
    "GridColumnWidthStyle": 1,
    "ActivateDialog": {
      "Type": "ActivateModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "DeactivateDialog": {
      "Type": "DeactivateModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 0,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    },
    "GetDirectionsDialog": {
      "Type": "GetDirectionsModal",
      "Title": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "PrimaryButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "CloseButtonText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "DismissButtonSrText": [
        {
          "Type": "LanguageResources",
          "LCID": 1033,
          "Value": ""
        }
      ],
      "Size": 1,
      "CssClass": "",
      "TitleCssClass": "",
      "PrimaryButtonCssClass": "",
      "CloseButtonCssClass": ""
    }
  }
adx_view: 9222d87d-fde5-4f04-ab97-1b8e0378b4ed
adx_views: >-
  {
    "Type": "ViewMetadata",
    "Views": [
      {
        "Type": "View",
        "ViewId": "9222d87d-fde5-4f04-ab97-1b8e0378b4ed",
        "DisplayName": [
          {
            "Type": "LanguageResources",
            "LCID": 1033,
            "Value": ""
          }
        ]
      }
    ]
  }
