adx_appendquerystring: false
adx_associatecurrentportaluser: true
adx_attachfile: false
adx_attachfileallowmultiple: false
adx_attachfilerequired: false
adx_attachfilerestrictaccept: false
adx_autogeneratesteps: false
adx_captcharequired: false
adx_entityformid: ae46f8ae-ee77-ed11-81ab-000d3a8c6ab8
adx_entityname: ava_application
adx_entitypermissionsenabled: true
adx_forceallfieldsrequired: false
adx_formname: Information - Simple EntityForm
adx_geolocation_displaymap: false
adx_geolocation_enabled: false
adx_hideformonsuccess: false
adx_name: Application Create
adx_populatereferenceentitylookupfield: false
adx_portaluserlookupattributeisactivityparty: false
adx_recommendedfieldsrequired: false
adx_recordsourceallowcreateonnull: false
adx_redirecturlappendentityidquerystring: false
adx_referenceentitylogicalname: contact
adx_referenceentityrelationshipname: ava_contact_ava_application_contactapplicant
adx_referenceentityshowreadonlyform: false
adx_referenceentitysourcetype: 756150001
adx_referencequerystringisprimarykey: true
adx_referencerecordsourcerelationshipname: contact_customer_contacts
adx_renderwebresourcesinline: false
adx_setentityreference: true
adx_showcaptchaforauthenticatedusers: false
adx_showownerfields: false
adx_showunsupportedfields: false
adx_tabname: GeneralInformation
adx_targetentityportaluserlookupattribute: ava_contactapplicant
adx_tooltipenabled: false
adx_validationsummarylinksenabled: true
