adx_allowmultiplefiles: false
adx_appendquerystring: false
adx_associatecurrentportaluser: true
adx_attachfile: false
adx_attachfilerequired: false
adx_attachfilerestrictaccept: false
adx_autogeneratesteps: false
adx_captcharequired: false
adx_createautonumber: false
adx_editexistingrecordpermitted: false
adx_entitypermissionsenabled: true
adx_forceallfieldsrequired: false
adx_formname: Information
adx_geolocation_displaymap: false
adx_geolocation_enabled: false
adx_hideformonsuccess: true
adx_loguser: false
adx_movepreviouspermitted: true
adx_multiplerecordsperuserpermitted: false
adx_name: Application Create - Step1
adx_nextstep: ffc3e569-987c-ed11-81ad-000d3a8c6ab8
adx_populatereferenceentitylookupfield: false
adx_portaluserlookupattributeisactivityparty: false
adx_recommendedfieldsrequired: false
adx_redirecturlappendentityidquerystring: false
adx_referenceentityshowreadonlyform: false
adx_referencequerystringisprimarykey: true
adx_renderwebresourcesinline: true
adx_setentityreference: false
adx_showcaptchaforauthenticatedusers: false
adx_showownerfields: false
adx_showunsupportedfields: false
adx_tabname: GeneralInformation
adx_targetentitylogicalname: ava_application
adx_targetentityportaluserlookupattribute: ava_contactapplicant
adx_tooltipenabled: false
adx_type: 100000002
adx_validationsummarylinksenabled: true
adx_webform: 6d2ef2bc-967c-ed11-81ad-000d3a8c6ab8
adx_webformstepid: e9019467-977c-ed11-81ad-000d3a8c6ab8
